import 'package:flutter/material.dart';
import 'package:stacked/stacked.dart';
import 'package:stacked_services/stacked_services.dart';

import '../../../../app/app.locator.dart';
import '../../../../app/router.dart';
import '../../../../core/models/models.dart';
import '../../../../core/services/api_service.dart';

class CreateShipmentViewModel extends BaseViewModel {
  final _apiService = locator<ApiService>();
  final _router = locator<AppRouter>();
  final _snackbarService = locator<SnackbarService>();

  // Form controllers
  final companyNameController = TextEditingController();
  final shipperNameController = TextEditingController();
  final shipperPhoneController = TextEditingController();
  final shipperAddressController = TextEditingController();
  final shipperCityController = TextEditingController();
  final shipperPostalController = TextEditingController();

  final consigneeCompanyController = TextEditingController();
  final receiverNameController = TextEditingController();
  final receiverEmailController = TextEditingController();
  final receiverPhoneController = TextEditingController();
  final receiverAddressController = TextEditingController();
  final receiverCityController = TextEditingController();
  final receiverZipController = TextEditingController();

  final accountNoController = TextEditingController();
  final piecesController = TextEditingController();
  final descriptionController = TextEditingController();
  final shipperReferenceController = TextEditingController();
  final commentsController = TextEditingController();

  final volumetricWeightController = TextEditingController();
  final lengthController = TextEditingController();
  final widthController = TextEditingController();
  final heightController = TextEditingController();
  final weightController = TextEditingController();

  // Selected values
  ServiceType? _selectedService;
  String? _shipperCountry;
  String? _receiverCountry;
  ShipmentType _shipmentType = ShipmentType.docs;
  bool _isFragile = false;
  CurrencyType _currency = CurrencyType.usd;
  InvoiceType? _invoiceType;

  // Getters
  ServiceType? get selectedService => _selectedService;
  String? get shipperCountry => _shipperCountry;
  String? get receiverCountry => _receiverCountry;
  ShipmentType get shipmentType => _shipmentType;
  bool get isFragile => _isFragile;
  CurrencyType get currency => _currency;
  InvoiceType? get invoiceType => _invoiceType;

  bool get showBoxDimensions => _shipmentType == ShipmentType.nonDocsBox;

  void setService(ServiceType? service) {
    _selectedService = service;
    notifyListeners();
  }

  void setShipperCountry(String? country) {
    _shipperCountry = country;
    notifyListeners();
  }

  void setReceiverCountry(String? country) {
    _receiverCountry = country;
    notifyListeners();
  }

  void setShipmentType(ShipmentType type) {
    _shipmentType = type;
    notifyListeners();
  }

  void setFragile(bool value) {
    _isFragile = value;
    notifyListeners();
  }

  void setCurrency(CurrencyType? curr) {
    if (curr != null) {
      _currency = curr;
      notifyListeners();
    }
  }

  void setInvoiceType(InvoiceType? type) {
    _invoiceType = type;
    notifyListeners();
  }

  Future<void> createShipment() async {
    // Validation
    if (!_validateForm()) {
      return;
    }

    setBusy(true);

    try {
      final shipment = Shipment(
        consigneeNumber: '', // Will be generated by API
        service: _selectedService!,
        status: ShipmentStatus.pending,
        companyName: companyNameController.text,
        shipperName: shipperNameController.text,
        shipperPhone: shipperPhoneController.text,
        shipperAddress: shipperAddressController.text,
        shipperCountry: _shipperCountry!,
        shipperCity: shipperCityController.text,
        shipperPostal: shipperPostalController.text,
        consigneeCompanyName: consigneeCompanyController.text,
        receiverName: receiverNameController.text,
        receiverEmail: receiverEmailController.text,
        receiverPhone: receiverPhoneController.text,
        receiverAddress: receiverAddressController.text,
        receiverCountry: _receiverCountry!,
        receiverCity: receiverCityController.text,
        receiverZip: receiverZipController.text,
        accountNo: accountNoController.text,
        shipmentType: _shipmentType,
        pieces: int.tryParse(piecesController.text) ?? 1,
        description: descriptionController.text,
        fragile: _isFragile,
        currency: _currency,
        shipperReference: shipperReferenceController.text.isEmpty
            ? null
            : shipperReferenceController.text,
        comments: commentsController.text.isEmpty ? null : commentsController.text,
        totalVolumetricWeight: volumetricWeightController.text.isEmpty
            ? null
            : double.tryParse(volumetricWeightController.text),
        dimensions: _buildDimensionsString(),
        weight: weightController.text.isEmpty
            ? null
            : double.tryParse(weightController.text),
        invoiceType: _invoiceType,
        createdAt: DateTime.now(),
      );

      await _apiService.createShipment(shipment);

      _snackbarService.showSnackbar(
        message: 'Shipment created successfully!',
        duration: const Duration(seconds: 2),
      );

      _router.maybePop();
    } catch (e) {
      _snackbarService.showSnackbar(
        message: 'Failed to create shipment: $e',
        duration: const Duration(seconds: 3),
      );
    } finally {
      setBusy(false);
    }
  }

  String? _buildDimensionsString() {
    if (lengthController.text.isEmpty &&
        widthController.text.isEmpty &&
        heightController.text.isEmpty) {
      return null;
    }
    return '${lengthController.text}x${widthController.text}x${heightController.text}';
  }

  bool _validateForm() {
    if (_selectedService == null) {
      _snackbarService.showSnackbar(
        message: 'Please select a service',
        duration: const Duration(seconds: 2),
      );
      return false;
    }

    if (companyNameController.text.isEmpty) {
      _snackbarService.showSnackbar(
        message: 'Please enter company name',
        duration: const Duration(seconds: 2),
      );
      return false;
    }

    if (shipperNameController.text.isEmpty) {
      _snackbarService.showSnackbar(
        message: 'Please enter shipper name',
        duration: const Duration(seconds: 2),
      );
      return false;
    }

    // Validate shipper phone number (only digits)
    if (shipperPhoneController.text.isNotEmpty) {
      if (!RegExp(r'^\d+$').hasMatch(shipperPhoneController.text)) {
        _snackbarService.showSnackbar(
          message: 'Shipper phone number must contain only digits',
          duration: const Duration(seconds: 2),
        );
        return false;
      }
    }

    if (_shipperCountry == null) {
      _snackbarService.showSnackbar(
        message: 'Please select shipper country',
        duration: const Duration(seconds: 2),
      );
      return false;
    }

    if (receiverNameController.text.isEmpty) {
      _snackbarService.showSnackbar(
        message: 'Please enter receiver name',
        duration: const Duration(seconds: 2),
      );
      return false;
    }

    // Validate receiver email format
    if (receiverEmailController.text.isNotEmpty) {
      if (!RegExp(r'^[\w-\.]+@([\w-]+\.)+[\w-]{2,4}$').hasMatch(receiverEmailController.text)) {
        _snackbarService.showSnackbar(
          message: 'Please enter a valid email address',
          duration: const Duration(seconds: 2),
        );
        return false;
      }
    }

    // Validate receiver phone number (only digits)
    if (receiverPhoneController.text.isNotEmpty) {
      if (!RegExp(r'^\d+$').hasMatch(receiverPhoneController.text)) {
        _snackbarService.showSnackbar(
          message: 'Receiver phone number must contain only digits',
          duration: const Duration(seconds: 2),
        );
        return false;
      }
    }

    if (_receiverCountry == null) {
      _snackbarService.showSnackbar(
        message: 'Please select receiver country',
        duration: const Duration(seconds: 2),
      );
      return false;
    }

    // Validate account number
    if (accountNoController.text.isEmpty) {
      _snackbarService.showSnackbar(
        message: 'Please enter account number',
        duration: const Duration(seconds: 2),
      );
      return false;
    }

    if (accountNoController.text.trim().isEmpty) {
      _snackbarService.showSnackbar(
        message: 'Account number cannot be empty',
        duration: const Duration(seconds: 2),
      );
      return false;
    }

    // Validate pieces
    if (piecesController.text.isEmpty) {
      _snackbarService.showSnackbar(
        message: 'Please enter number of pieces',
        duration: const Duration(seconds: 2),
      );
      return false;
    }

    final pieces = int.tryParse(piecesController.text);
    if (pieces == null || pieces <= 0) {
      _snackbarService.showSnackbar(
        message: 'Pieces must be a valid number greater than 0',
        duration: const Duration(seconds: 2),
      );
      return false;
    }

    if (descriptionController.text.isEmpty) {
      _snackbarService.showSnackbar(
        message: 'Please enter description',
        duration: const Duration(seconds: 2),
      );
      return false;
    }

    // Validate box dimensions if shipment type is box
    if (_shipmentType == ShipmentType.nonDocsBox) {
      if (lengthController.text.isEmpty ||
          widthController.text.isEmpty ||
          heightController.text.isEmpty) {
        _snackbarService.showSnackbar(
          message: 'Please enter all box dimensions (length, width, height)',
          duration: const Duration(seconds: 2),
        );
        return false;
      }

      final length = double.tryParse(lengthController.text);
      final width = double.tryParse(widthController.text);
      final height = double.tryParse(heightController.text);

      if (length == null || length <= 0) {
        _snackbarService.showSnackbar(
          message: 'Length must be a valid number greater than 0',
          duration: const Duration(seconds: 2),
        );
        return false;
      }

      if (width == null || width <= 0) {
        _snackbarService.showSnackbar(
          message: 'Width must be a valid number greater than 0',
          duration: const Duration(seconds: 2),
        );
        return false;
      }

      if (height == null || height <= 0) {
        _snackbarService.showSnackbar(
          message: 'Height must be a valid number greater than 0',
          duration: const Duration(seconds: 2),
        );
        return false;
      }

      if (weightController.text.isNotEmpty) {
        final weight = double.tryParse(weightController.text);
        if (weight == null || weight <= 0) {
          _snackbarService.showSnackbar(
            message: 'Weight must be a valid number greater than 0',
            duration: const Duration(seconds: 2),
          );
          return false;
        }
      }

      if (volumetricWeightController.text.isNotEmpty) {
        final volWeight = double.tryParse(volumetricWeightController.text);
        if (volWeight == null || volWeight <= 0) {
          _snackbarService.showSnackbar(
            message: 'Volumetric weight must be a valid number greater than 0',
            duration: const Duration(seconds: 2),
          );
          return false;
        }
      }
    }

    return true;
  }

  @override
  void dispose() {
    companyNameController.dispose();
    shipperNameController.dispose();
    shipperPhoneController.dispose();
    shipperAddressController.dispose();
    shipperCityController.dispose();
    shipperPostalController.dispose();
    consigneeCompanyController.dispose();
    receiverNameController.dispose();
    receiverEmailController.dispose();
    receiverPhoneController.dispose();
    receiverAddressController.dispose();
    receiverCityController.dispose();
    receiverZipController.dispose();
    accountNoController.dispose();
    piecesController.dispose();
    descriptionController.dispose();
    shipperReferenceController.dispose();
    commentsController.dispose();
    volumetricWeightController.dispose();
    lengthController.dispose();
    widthController.dispose();
    heightController.dispose();
    weightController.dispose();
    super.dispose();
  }
}
