import 'package:flutter/material.dart';
import 'package:stacked/stacked.dart';
import 'package:stacked_services/stacked_services.dart';

import '../../../app/app.locator.dart';
import '../../../core/models/models.dart';
import '../../../core/services/api_service.dart';

class UsersViewModel extends BaseViewModel {
  final _apiService = locator<ApiService>();
  final _snackbarService = locator<SnackbarService>();

  List<User> _users = [];
  List<User> get users => _users;

  // Form controllers for create/edit
  final emailController = TextEditingController();
  final fullNameController = TextEditingController();
  final phoneController = TextEditingController();
  String _selectedRole = 'user';
  bool _isActive = true;

  String get selectedRole => _selectedRole;
  bool get isActive => _isActive;

  // Edit mode
  User? _editingUser;
  User? get editingUser => _editingUser;

  void initialize() {
    loadUsers();
  }

  Future<void> loadUsers() async {
    setBusy(true);
    try {
      _users = await _apiService.getUsers();
      notifyListeners();
    } catch (e) {
      _snackbarService.showSnackbar(
        message: 'Failed to load users: $e',
        duration: const Duration(seconds: 3),
      );
    } finally {
      setBusy(false);
    }
  }

  void setRole(String? role) {
    if (role != null) {
      _selectedRole = role;
      notifyListeners();
    }
  }

  void setIsActive(bool value) {
    _isActive = value;
    notifyListeners();
  }

  void startCreateUser() {
    _editingUser = null;
    emailController.clear();
    fullNameController.clear();
    phoneController.clear();
    _selectedRole = 'user';
    _isActive = true;
    notifyListeners();
  }

  void startEditUser(User user) {
    _editingUser = user;
    emailController.text = user.email;
    fullNameController.text = user.fullName;
    phoneController.text = user.phone ?? '';
    _selectedRole = user.role;
    _isActive = user.isActive;
    notifyListeners();
  }

  Future<bool> saveUser() async {
    // Validation
    if (emailController.text.isEmpty) {
      _snackbarService.showSnackbar(
        message: 'Please enter email',
        duration: const Duration(seconds: 2),
      );
      return false;
    }

    if (fullNameController.text.isEmpty) {
      _snackbarService.showSnackbar(
        message: 'Please enter full name',
        duration: const Duration(seconds: 2),
      );
      return false;
    }

    setBusy(true);
    try {
      if (_editingUser == null) {
        // Create new user
        final user = User(
          id: '', // Will be generated by API
          email: emailController.text,
          fullName: fullNameController.text,
          phone: phoneController.text.isEmpty ? null : phoneController.text,
          role: _selectedRole,
          isActive: _isActive,
          createdAt: DateTime.now(),
        );

        await _apiService.createUser(user);
        _snackbarService.showSnackbar(
          message: 'User created successfully!',
          duration: const Duration(seconds: 2),
        );
      } else {
        // Update existing user
        final updatedUser = _editingUser!.copyWith(
          email: emailController.text,
          fullName: fullNameController.text,
          phone: phoneController.text.isEmpty ? null : phoneController.text,
          role: _selectedRole,
          isActive: _isActive,
        );

        await _apiService.updateUser(updatedUser);
        _snackbarService.showSnackbar(
          message: 'User updated successfully!',
          duration: const Duration(seconds: 2),
        );
      }

      await loadUsers();
      return true;
    } catch (e) {
      _snackbarService.showSnackbar(
        message: 'Failed to save user: $e',
        duration: const Duration(seconds: 3),
      );
      return false;
    } finally {
      setBusy(false);
    }
  }

  Future<void> deleteUser(User user) async {
    setBusy(true);
    try {
      await _apiService.deleteUser(user.id);
      _snackbarService.showSnackbar(
        message: 'User deleted successfully!',
        duration: const Duration(seconds: 2),
      );
      await loadUsers();
    } catch (e) {
      _snackbarService.showSnackbar(
        message: 'Failed to delete user: $e',
        duration: const Duration(seconds: 3),
      );
    } finally {
      setBusy(false);
    }
  }

  @override
  void dispose() {
    emailController.dispose();
    fullNameController.dispose();
    phoneController.dispose();
    super.dispose();
  }
}
